# Generated by Django 4.2.5 on 2023-10-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0003_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='producto'),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
