# Generated by Django 4.2.5 on 2023-10-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0004_delete_cliente_remove_comentario_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='', max_length=40)),
                ('tipo', models.CharField(max_length=40)),
                ('calificacion', models.FloatField()),
                ('opinion', models.TextField(max_length=300)),
            ],
        ),
    ]
