# Generated by Django 4.2.5 on 2023-10-19 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0005_comentario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
