# Generated by Django 4.2.5 on 2023-10-27 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0007_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='estrenos'),
        ),
    ]
