# Generated by Django 4.2.5 on 2023-10-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0008_comentario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes'),
        ),
    ]
