# Generated by Django 4.2.5 on 2023-10-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appweb', '0012_comentario_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='jabones'),
        ),
    ]
